// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Room.proto

package com.uosipa.chatuvolchat.protocol.room;

public final class Room {
  private Room() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.uosipa.chatuvolchat.protocol.room.Room.chatMessage);
  }
  public static final class ChatMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage() {
      initFields();
    }
    private ChatMessage(boolean noInit) {}
    
    private static final ChatMessage defaultInstance;
    public static ChatMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.uosipa.chatuvolchat.protocol.room.Room.internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.uosipa.chatuvolchat.protocol.room.Room.internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_fieldAccessorTable;
    }
    
    public static final class Request extends
        com.google.protobuf.GeneratedMessage {
      // Use Request.newBuilder() to construct.
      private Request() {
        initFields();
      }
      private Request(boolean noInit) {}
      
      private static final Request defaultInstance;
      public static Request getDefaultInstance() {
        return defaultInstance;
      }
      
      public Request getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.uosipa.chatuvolchat.protocol.room.Room.internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.uosipa.chatuvolchat.protocol.room.Room.internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Request_fieldAccessorTable;
      }
      
      // required int32 room_id = 1;
      public static final int ROOM_ID_FIELD_NUMBER = 1;
      private boolean hasRoomId;
      private int roomId_ = 0;
      public boolean hasRoomId() { return hasRoomId; }
      public int getRoomId() { return roomId_; }
      
      // required string message = 2;
      public static final int MESSAGE_FIELD_NUMBER = 2;
      private boolean hasMessage;
      private java.lang.String message_ = "";
      public boolean hasMessage() { return hasMessage; }
      public java.lang.String getMessage() { return message_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasRoomId) return false;
        if (!hasMessage) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasRoomId()) {
          output.writeInt32(1, getRoomId());
        }
        if (hasMessage()) {
          output.writeString(2, getMessage());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasRoomId()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, getRoomId());
        }
        if (hasMessage()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getMessage());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request result;
        
        // Construct using com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request();
          return builder;
        }
        
        protected com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.getDescriptor();
        }
        
        public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request getDefaultInstanceForType() {
          return com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request) {
            return mergeFrom((com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request other) {
          if (other == com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.getDefaultInstance()) return this;
          if (other.hasRoomId()) {
            setRoomId(other.getRoomId());
          }
          if (other.hasMessage()) {
            setMessage(other.getMessage());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setRoomId(input.readInt32());
                break;
              }
              case 18: {
                setMessage(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required int32 room_id = 1;
        public boolean hasRoomId() {
          return result.hasRoomId();
        }
        public int getRoomId() {
          return result.getRoomId();
        }
        public Builder setRoomId(int value) {
          result.hasRoomId = true;
          result.roomId_ = value;
          return this;
        }
        public Builder clearRoomId() {
          result.hasRoomId = false;
          result.roomId_ = 0;
          return this;
        }
        
        // required string message = 2;
        public boolean hasMessage() {
          return result.hasMessage();
        }
        public java.lang.String getMessage() {
          return result.getMessage();
        }
        public Builder setMessage(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
          result.message_ = value;
          return this;
        }
        public Builder clearMessage() {
          result.hasMessage = false;
          result.message_ = getDefaultInstance().getMessage();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:com.uosipa.chatuvolchat.protocol.room.ChatMessage.Request)
      }
      
      static {
        defaultInstance = new Request(true);
        com.uosipa.chatuvolchat.protocol.room.Room.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.uosipa.chatuvolchat.protocol.room.ChatMessage.Request)
    }
    
    public static final class Response extends
        com.google.protobuf.GeneratedMessage {
      // Use Response.newBuilder() to construct.
      private Response() {
        initFields();
      }
      private Response(boolean noInit) {}
      
      private static final Response defaultInstance;
      public static Response getDefaultInstance() {
        return defaultInstance;
      }
      
      public Response getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.uosipa.chatuvolchat.protocol.room.Room.internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.uosipa.chatuvolchat.protocol.room.Room.internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Response_fieldAccessorTable;
      }
      
      // required .com.uosipa.chatuvolchat.protocol.stuff.Status status = 1;
      public static final int STATUS_FIELD_NUMBER = 1;
      private boolean hasStatus;
      private com.uosipa.chatuvolchat.protocol.stuff.Stuff.Status status_;
      public boolean hasStatus() { return hasStatus; }
      public com.uosipa.chatuvolchat.protocol.stuff.Stuff.Status getStatus() { return status_; }
      
      private void initFields() {
        status_ = com.uosipa.chatuvolchat.protocol.stuff.Stuff.Status.OK;
      }
      public final boolean isInitialized() {
        if (!hasStatus) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasStatus()) {
          output.writeEnum(1, getStatus().getNumber());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasStatus()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, getStatus().getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response result;
        
        // Construct using com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response();
          return builder;
        }
        
        protected com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.getDescriptor();
        }
        
        public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response getDefaultInstanceForType() {
          return com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response) {
            return mergeFrom((com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response other) {
          if (other == com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.getDefaultInstance()) return this;
          if (other.hasStatus()) {
            setStatus(other.getStatus());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                com.uosipa.chatuvolchat.protocol.stuff.Stuff.Status value = com.uosipa.chatuvolchat.protocol.stuff.Stuff.Status.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  setStatus(value);
                }
                break;
              }
            }
          }
        }
        
        
        // required .com.uosipa.chatuvolchat.protocol.stuff.Status status = 1;
        public boolean hasStatus() {
          return result.hasStatus();
        }
        public com.uosipa.chatuvolchat.protocol.stuff.Stuff.Status getStatus() {
          return result.getStatus();
        }
        public Builder setStatus(com.uosipa.chatuvolchat.protocol.stuff.Stuff.Status value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hasStatus = true;
          result.status_ = value;
          return this;
        }
        public Builder clearStatus() {
          result.hasStatus = false;
          result.status_ = com.uosipa.chatuvolchat.protocol.stuff.Stuff.Status.OK;
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:com.uosipa.chatuvolchat.protocol.room.ChatMessage.Response)
      }
      
      static {
        defaultInstance = new Response(true);
        com.uosipa.chatuvolchat.protocol.room.Room.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.uosipa.chatuvolchat.protocol.room.ChatMessage.Response)
    }
    
    public static final class Notification extends
        com.google.protobuf.GeneratedMessage {
      // Use Notification.newBuilder() to construct.
      private Notification() {
        initFields();
      }
      private Notification(boolean noInit) {}
      
      private static final Notification defaultInstance;
      public static Notification getDefaultInstance() {
        return defaultInstance;
      }
      
      public Notification getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.uosipa.chatuvolchat.protocol.room.Room.internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Notification_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.uosipa.chatuvolchat.protocol.room.Room.internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Notification_fieldAccessorTable;
      }
      
      // required int32 room_id = 1;
      public static final int ROOM_ID_FIELD_NUMBER = 1;
      private boolean hasRoomId;
      private int roomId_ = 0;
      public boolean hasRoomId() { return hasRoomId; }
      public int getRoomId() { return roomId_; }
      
      // required string name = 2;
      public static final int NAME_FIELD_NUMBER = 2;
      private boolean hasName;
      private java.lang.String name_ = "";
      public boolean hasName() { return hasName; }
      public java.lang.String getName() { return name_; }
      
      // required string message = 3;
      public static final int MESSAGE_FIELD_NUMBER = 3;
      private boolean hasMessage;
      private java.lang.String message_ = "";
      public boolean hasMessage() { return hasMessage; }
      public java.lang.String getMessage() { return message_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasRoomId) return false;
        if (!hasName) return false;
        if (!hasMessage) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasRoomId()) {
          output.writeInt32(1, getRoomId());
        }
        if (hasName()) {
          output.writeString(2, getName());
        }
        if (hasMessage()) {
          output.writeString(3, getMessage());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasRoomId()) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, getRoomId());
        }
        if (hasName()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getName());
        }
        if (hasMessage()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(3, getMessage());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification result;
        
        // Construct using com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification();
          return builder;
        }
        
        protected com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.getDescriptor();
        }
        
        public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification getDefaultInstanceForType() {
          return com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification) {
            return mergeFrom((com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification other) {
          if (other == com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.getDefaultInstance()) return this;
          if (other.hasRoomId()) {
            setRoomId(other.getRoomId());
          }
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasMessage()) {
            setMessage(other.getMessage());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 8: {
                setRoomId(input.readInt32());
                break;
              }
              case 18: {
                setName(input.readString());
                break;
              }
              case 26: {
                setMessage(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required int32 room_id = 1;
        public boolean hasRoomId() {
          return result.hasRoomId();
        }
        public int getRoomId() {
          return result.getRoomId();
        }
        public Builder setRoomId(int value) {
          result.hasRoomId = true;
          result.roomId_ = value;
          return this;
        }
        public Builder clearRoomId() {
          result.hasRoomId = false;
          result.roomId_ = 0;
          return this;
        }
        
        // required string name = 2;
        public boolean hasName() {
          return result.hasName();
        }
        public java.lang.String getName() {
          return result.getName();
        }
        public Builder setName(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
          result.name_ = value;
          return this;
        }
        public Builder clearName() {
          result.hasName = false;
          result.name_ = getDefaultInstance().getName();
          return this;
        }
        
        // required string message = 3;
        public boolean hasMessage() {
          return result.hasMessage();
        }
        public java.lang.String getMessage() {
          return result.getMessage();
        }
        public Builder setMessage(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
          result.message_ = value;
          return this;
        }
        public Builder clearMessage() {
          result.hasMessage = false;
          result.message_ = getDefaultInstance().getMessage();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:com.uosipa.chatuvolchat.protocol.room.ChatMessage.Notification)
      }
      
      static {
        defaultInstance = new Notification(true);
        com.uosipa.chatuvolchat.protocol.room.Room.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.uosipa.chatuvolchat.protocol.room.ChatMessage.Notification)
    }
    
    // optional .com.uosipa.chatuvolchat.protocol.room.ChatMessage.Request request = 1;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private boolean hasRequest;
    private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request request_;
    public boolean hasRequest() { return hasRequest; }
    public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request getRequest() { return request_; }
    
    // optional .com.uosipa.chatuvolchat.protocol.room.ChatMessage.Response response = 2;
    public static final int RESPONSE_FIELD_NUMBER = 2;
    private boolean hasResponse;
    private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response response_;
    public boolean hasResponse() { return hasResponse; }
    public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response getResponse() { return response_; }
    
    // optional .com.uosipa.chatuvolchat.protocol.room.ChatMessage.Notification notification = 3;
    public static final int NOTIFICATION_FIELD_NUMBER = 3;
    private boolean hasNotification;
    private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification notification_;
    public boolean hasNotification() { return hasNotification; }
    public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification getNotification() { return notification_; }
    
    private void initFields() {
      request_ = com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.getDefaultInstance();
      response_ = com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.getDefaultInstance();
      notification_ = com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasRequest()) {
        if (!getRequest().isInitialized()) return false;
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) return false;
      }
      if (hasNotification()) {
        if (!getNotification().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRequest()) {
        output.writeMessage(1, getRequest());
      }
      if (hasResponse()) {
        output.writeMessage(2, getResponse());
      }
      if (hasNotification()) {
        output.writeMessage(3, getNotification());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (hasResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponse());
      }
      if (hasNotification()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getNotification());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage result;
      
      // Construct using com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage();
        return builder;
      }
      
      protected com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.getDescriptor();
      }
      
      public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage getDefaultInstanceForType() {
        return com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage) {
          return mergeFrom((com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage other) {
        if (other == com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.hasNotification()) {
          mergeNotification(other.getNotification());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.Builder subBuilder = com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.newBuilder();
              if (hasRequest()) {
                subBuilder.mergeFrom(getRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRequest(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.Builder subBuilder = com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.newBuilder();
              if (hasResponse()) {
                subBuilder.mergeFrom(getResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setResponse(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.Builder subBuilder = com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.newBuilder();
              if (hasNotification()) {
                subBuilder.mergeFrom(getNotification());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNotification(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.uosipa.chatuvolchat.protocol.room.ChatMessage.Request request = 1;
      public boolean hasRequest() {
        return result.hasRequest();
      }
      public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request getRequest() {
        return result.getRequest();
      }
      public Builder setRequest(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRequest = true;
        result.request_ = value;
        return this;
      }
      public Builder setRequest(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.Builder builderForValue) {
        result.hasRequest = true;
        result.request_ = builderForValue.build();
        return this;
      }
      public Builder mergeRequest(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request value) {
        if (result.hasRequest() &&
            result.request_ != com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.getDefaultInstance()) {
          result.request_ =
            com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.newBuilder(result.request_).mergeFrom(value).buildPartial();
        } else {
          result.request_ = value;
        }
        result.hasRequest = true;
        return this;
      }
      public Builder clearRequest() {
        result.hasRequest = false;
        result.request_ = com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.getDefaultInstance();
        return this;
      }
      
      // optional .com.uosipa.chatuvolchat.protocol.room.ChatMessage.Response response = 2;
      public boolean hasResponse() {
        return result.hasResponse();
      }
      public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response getResponse() {
        return result.getResponse();
      }
      public Builder setResponse(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasResponse = true;
        result.response_ = value;
        return this;
      }
      public Builder setResponse(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.Builder builderForValue) {
        result.hasResponse = true;
        result.response_ = builderForValue.build();
        return this;
      }
      public Builder mergeResponse(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response value) {
        if (result.hasResponse() &&
            result.response_ != com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.getDefaultInstance()) {
          result.response_ =
            com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.newBuilder(result.response_).mergeFrom(value).buildPartial();
        } else {
          result.response_ = value;
        }
        result.hasResponse = true;
        return this;
      }
      public Builder clearResponse() {
        result.hasResponse = false;
        result.response_ = com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.getDefaultInstance();
        return this;
      }
      
      // optional .com.uosipa.chatuvolchat.protocol.room.ChatMessage.Notification notification = 3;
      public boolean hasNotification() {
        return result.hasNotification();
      }
      public com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification getNotification() {
        return result.getNotification();
      }
      public Builder setNotification(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasNotification = true;
        result.notification_ = value;
        return this;
      }
      public Builder setNotification(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.Builder builderForValue) {
        result.hasNotification = true;
        result.notification_ = builderForValue.build();
        return this;
      }
      public Builder mergeNotification(com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification value) {
        if (result.hasNotification() &&
            result.notification_ != com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.getDefaultInstance()) {
          result.notification_ =
            com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.newBuilder(result.notification_).mergeFrom(value).buildPartial();
        } else {
          result.notification_ = value;
        }
        result.hasNotification = true;
        return this;
      }
      public Builder clearNotification() {
        result.hasNotification = false;
        result.notification_ = com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.uosipa.chatuvolchat.protocol.room.ChatMessage)
    }
    
    static {
      defaultInstance = new ChatMessage(true);
      com.uosipa.chatuvolchat.protocol.room.Room.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.uosipa.chatuvolchat.protocol.room.ChatMessage)
  }
  
  public static final int CHAT_MESSAGE_FIELD_NUMBER = 11;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.uosipa.chatuvolchat.protocol.Interop.MessageContainer,
      com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage> chatMessage =
        com.google.protobuf.GeneratedMessage
          .newGeneratedExtension();
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Notification_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Notification_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRoom.proto\022%com.uosipa.chatuvolchat.pr" +
      "otocol.room\032\rInterop.proto\032\013Stuff.proto\"" +
      "\271\003\n\013ChatMessage\022K\n\007request\030\001 \001(\0132:.com.u" +
      "osipa.chatuvolchat.protocol.room.ChatMes" +
      "sage.Request\022M\n\010response\030\002 \001(\0132;.com.uos" +
      "ipa.chatuvolchat.protocol.room.ChatMessa" +
      "ge.Response\022U\n\014notification\030\003 \001(\0132?.com." +
      "uosipa.chatuvolchat.protocol.room.ChatMe" +
      "ssage.Notification\032+\n\007Request\022\017\n\007room_id" +
      "\030\001 \002(\005\022\017\n\007message\030\002 \002(\t\032J\n\010Response\022>\n\006s",
      "tatus\030\001 \002(\0162..com.uosipa.chatuvolchat.pr" +
      "otocol.stuff.Status\032>\n\014Notification\022\017\n\007r" +
      "oom_id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\017\n\007message\030\003 " +
      "\002(\t:|\n\014chat_message\0222.com.uosipa.chatuvo" +
      "lchat.protocol.MessageContainer\030\013 \001(\01322." +
      "com.uosipa.chatuvolchat.protocol.room.Ch" +
      "atMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_descriptor,
              new java.lang.String[] { "Request", "Response", "Notification", },
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.class,
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Builder.class);
          internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Request_descriptor =
            internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_descriptor.getNestedTypes().get(0);
          internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Request_descriptor,
              new java.lang.String[] { "RoomId", "Message", },
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.class,
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Request.Builder.class);
          internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Response_descriptor =
            internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_descriptor.getNestedTypes().get(1);
          internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Response_descriptor,
              new java.lang.String[] { "Status", },
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.class,
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Response.Builder.class);
          internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Notification_descriptor =
            internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_descriptor.getNestedTypes().get(2);
          internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Notification_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_uosipa_chatuvolchat_protocol_room_ChatMessage_Notification_descriptor,
              new java.lang.String[] { "RoomId", "Name", "Message", },
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.class,
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.Notification.Builder.class);
          com.uosipa.chatuvolchat.protocol.room.Room.chatMessage.internalInit(
              com.uosipa.chatuvolchat.protocol.room.Room.getDescriptor().getExtensions().get(0),
              com.uosipa.chatuvolchat.protocol.room.Room.ChatMessage.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.uosipa.chatuvolchat.protocol.Interop.getDescriptor(),
          com.uosipa.chatuvolchat.protocol.stuff.Stuff.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
